# Generated by Django 6.0.2 on 2026-02-09 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.TextField()),
                ('salt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_reads', models.IntegerField(blank=True, null=True)),
                ('read_count', models.IntegerField(default=0)),
            ],
        ),
    ]
