# Generated by Django 6.0.2 on 2026-02-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='nonce',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
