# Generated by Django 6.0.2 on 2026-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0002_secret_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
